In [1]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
import pandas as pd
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

desc = 'descrittore_finale_games.xlsx'
desc_read = pd.read_excel( desc )
desc_data = pd.DataFrame( desc_read )
# ATTENZIONE ALLA COLONNA DA ELIMINARE
desc_data = desc_data.iloc[:,2:]
desc_data

1diff_Top50  1diff_Top40  1diff_Top30  1diff_Top25  1diff_Top20  \
0                0            0            0            1            1   
1                0            0            0            0           -1   
2                0            0            0           -1           -1   
3               -1           -1           -1           -1            0   
4                0            0            0            0            0   
...            ...          ...          ...          ...          ...   
12265            1            1            1            1            0   
12266            0            0            0            0            0   
12267            0            0            0            1            0   
12268            1            1            1            1            0   
12269            0            0            0            0            0   

       1diff_Top15  1diff_Top10  1diff_Top5  2diff_Top50  2diff_Top40  ...  \
0                1            0           0            0            1  ...   
1               -1           -1          -1            0           -1  ...   
2               -1           -1          -1            0           -1  ...   
3                0            0           0            0            1  ...   
4                0            0           0           -1           -1  ...   
...            ...          ...         ...          ...          ...  ...   
12265            0            0           0            1            1  ...   
12266            0            0           0            0            0  ...   
12267            0            0           0            0            0  ...   
12268            0            0           0            1            1  ...   
12269            0            0           0            0            0  ...   

       Last_36month_SLAMProba_n1_win_set1_loose_set2  \
0                                          10.596505   
1                                          22.618766   
2                                          17.396638   
3                                          18.992042   
4                                          22.362136   
...                                              ...   
12265                                      45.223349   
12266                                      33.754797   
12267                                      26.511799   
12268                                      29.124663   
12269                                       0.000000   

       Last_36month_SLAMProba_n1_win_in_3sets  \
0                                    0.000000   
1                                   10.613771   
2                                    7.912850   
3                                    8.294154   
4                                    9.047715   
...                                       ...   
12265                               20.638292   
12266                               13.817376   
12267                               12.099021   
12268                               13.291437   
12269                                0.000000   

       Last_36month_SLAMProba_n1_loose_in_3sets  \
0                                      8.300251   
1                                      5.148548   
2                                      5.121087   
3                                      6.471509   
4                                     12.882980   
...                                         ...   
12265                                 18.923691   
12266                                 13.817376   
12267                                 11.093851   
12268                                 12.187203   
12269                                  0.000000   

       Last_36month_SLAMProba_n2_win_set1  \
0                               38.879191   
1                               63.355235   
2                               66.217755   
3                               51.351568   
4                               47.969118   
...                                 

In [2]:
riga_zero = desc_data.iloc[0,:]
for idx, v in enumerate ( riga_zero ):
    print( idx, type( v ) )

0 <class 'float'>
1 <class 'float'>
2 <class 'float'>
3 <class 'float'>
4 <class 'float'>
5 <class 'float'>
6 <class 'float'>
7 <class 'float'>
8 <class 'float'>
9 <class 'float'>
10 <class 'float'>
11 <class 'float'>
12 <class 'float'>
13 <class 'float'>
14 <class 'float'>
15 <class 'float'>
16 <class 'float'>
17 <class 'float'>
18 <class 'float'>
19 <class 'float'>
20 <class 'float'>
21 <class 'float'>
22 <class 'float'>
23 <class 'float'>
24 <class 'float'>
25 <class 'float'>
26 <class 'float'>
27 <class 'float'>
28 <class 'float'>
29 <class 'float'>
30 <class 'float'>
31 <class 'float'>
32 <class 'float'>
33 <class 'float'>
34 <class 'float'>
35 <class 'float'>
36 <class 'float'>
37 <class 'float'>
38 <class 'float'>
39 <class 'float'>
40 <class 'float'>
41 <class 'float'>
42 <class 'float'>
43 <class 'float'>
44 <class 'float'>
45 <class 'float'>
46 <class 'float'>
47 <class 'float'>
48 <class 'float'>
49 <class 'float'>
50 <class 'float'>
51 <class 'float'>
52 <class 'float'>
53 

In [3]:
target = 'file_target_data_2005_games.xlsx'
target_read = pd.read_excel( target )
target_data = pd.DataFrame( target_read )
#target_data = target_data.loc[ target_data.data_parsed>'2005-01-01' ]
target_data

Unnamed: 0  Unnamed: 0.1                                       PARTITE  \
0            1830           771      QRT_GROSJEAN_DAVYDENKO_3_DOHA_2005_HARD_   
1            1831           765          F_LJUBICIC_FEDERER_3_DOHA_2005_HARD_   
2            1832           766        SF_DAVYDENKO_FEDERER_3_DOHA_2005_HARD_   
3            1833           767           SF_COSTA_LJUBICIC_3_DOHA_2005_HARD_   
4            1834           768           QRT_SANTORO_COSTA_3_DOHA_2005_HARD_   
...           ...           ...                                           ...   
12265       14365          6963       QRT_ISNER_O'CONNELL_3_ATLANTA_2021_HARD   
12266       14366          6962   SF_NAKASHIMA_RUUSUVUORI_3_ATLANTA_2021_HARD   
12267       14367          6961            SF_ISNER_FRITZ_3_ATLANTA_2021_HARD   
12268       14368          6960         F_ISNER_NAKASHIMA_3_ATLANTA_2021_HARD   
12269       14369          7127  SF_RUUSUVUORI_NAKASHIMA_3_ATLANTA_2021_HARD_   

       set_p1  set_p2 games_1_set1 games_1_set2 games_1_set3 games_2_set1  \
0           1       2            6            3            2            2   
1           0       2            3            1                         6   
2           0       2            3            4                         6   
3           0       2            3            6                         6   
4           0       1            2            0                         6   
...       ...     ...          ...          ...          ...          ...   
12265       2       1            7           63            6           65   
12266       2       1            3            6            6            6   
12267       2       1            7            5            6           64   
12268       2       0            7            7                        68   
12269       1       2            6            4            3            3   

      games_2_set2 games_2_set3  segno data_parsed  unicode  
0                6            6      2  2005-01-03     1831  
1                6                   2  2005-01-03     1832  
2                6                   2  2005-01-03     1833  
3                7                   2  2005-01-03     1834  
4                3                   2  2005-01-03     1835  
...            ...          ...    ...         ...      ...  
12265            7            4      1  2021-07-26    14366  
12266            4            3      1  2021-07-26    14367  
12267            7            3      1  2021-07-26    14368  
12268            5                   1  2021-07-26    14369  
12269            6            6      2  2021-07-26    14370  

[12270 rows x 14 columns]

In [4]:
SEGNO = target_data.iloc[:,11]
SEGNO

0        2
1        2
2        2
3        2
4        2
        ..
12265    1
12266    1
12267    1
12268    1
12269    2
Name: segno, Length: 12270, dtype: int64

In [5]:
conto_3 = 0
conto_4 = 0
idx_1 = []
idx_2 = []
idx_3 = []
idx_4 = []

for idx, v in enumerate ( SEGNO ) :
    if v==3 :
        conto_3 = conto_3+1
        idx_3.append( idx )
    elif v==4 :
        conto_4 = conto_4+1
        idx_4.append( idx )
    elif v==1 :
        idx_1.append( idx )
    elif v==2 :
        idx_2.append( idx )
        
print("Len 3: ", conto_3 )
print("Len 4: ", conto_4 )
print("Lista idx==1 : ", idx_1 )
print("Lista idx==2 : ", idx_2 )



Len 3:  0
Len 4:  0
Lista idx==1 :  [10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23, 24, 29, 32, 34, 35, 36, 47, 48, 49, 50, 52, 54, 55, 56, 62, 66, 70, 72, 74, 75, 76, 77, 78, 79, 80, 81, 83, 85, 86, 87, 88, 89, 90, 92, 93, 107, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 121, 123, 124, 125, 126, 136, 138, 139, 140, 141, 142, 144, 145, 160, 161, 162, 163, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 223, 226, 230, 232, 233, 235, 238, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 268, 269, 275, 281, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 296, 297, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 311, 313, 336, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 353, 354, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 378, 384, 393, 394, 395, 396, 398, 399, 400, 401, 402, 4

In [6]:
desc_data_1 = desc_data.iloc[ idx_1, :]
desc_data_1

1diff_Top50  1diff_Top40  1diff_Top30  1diff_Top25  1diff_Top20  \
10               0            1            1            0            0   
11               1            1            1            1            0   
12               0            0            0            0            0   
13               0            0            0            0            0   
14              -1           -1            0            0            0   
...            ...          ...          ...          ...          ...   
12264            0            0            0            0            0   
12265            1            1            1            1            0   
12266            0            0            0            0            0   
12267            0            0            0            1            0   
12268            1            1            1            1            0   

       1diff_Top15  1diff_Top10  1diff_Top5  2diff_Top50  2diff_Top40  ...  \
10               0            0           0            1            0  ...   
11               0            0           0            1            1  ...   
12               0            0           0            0            0  ...   
13               0            0           0            1            1  ...   
14               0            0           0            1            0  ...   
...            ...          ...         ...          ...          ...  ...   
12264            0            0           0            0            0  ...   
12265            0            0           0            1            1  ...   
12266            0            0           0            0            0  ...   
12267            0            0           0            0            0  ...   
12268            0            0           0            1            1  ...   

       Last_36month_SLAMProba_n1_win_set1_loose_set2  \
10                                         36.318794   
11                                         34.677627   
12                                         35.246897   
13                                         39.039371   
14                                          9.345104   
...                                              ...   
12264                                       0.000000   
12265                                      45.223349   
12266                                      33.754797   
12267                                      26.511799   
12268                                      29.124663   

       Last_36month_SLAMProba_n1_win_in_3sets  \
10                                  16.519582   
11                                  14.631832   
12                                  14.260887   
13                                  17.049169   
14                                   0.000000   
...                                       ...   
12264                                0.000000   
12265                               20.638292   
12266                               13.817376   
12267                               12.099021   
12268                               13.291437   

       Last_36month_SLAMProba_n1_loose_in_3sets  \
10                                    10.691244   
11                                    14.631832   
12                                    20.305979   
13                                    13.302606   
14                                     6.005939   
...                                         ...   
12264                                  0.000000   
12265                                 18.923691   
12266                                 13.817376   
12267                                 11.093851   
12268                                 12.187203   

       Last_36month_SLAMProba_n2_win_set1  \
10                              29.473131   
11                               0.000000   
12                              17.989625   
13                               0.000000   
14                              43.267653   
...                                 

In [7]:
desc_data_2 = desc_data.iloc[idx_2, :]
desc_data_2

1diff_Top50  1diff_Top40  1diff_Top30  1diff_Top25  1diff_Top20  \
0                0            0            0            1            1   
1                0            0            0            0           -1   
2                0            0            0           -1           -1   
3               -1           -1           -1           -1            0   
4                0            0            0            0            0   
...            ...          ...          ...          ...          ...   
12250            0            0            0            0            0   
12251           -1           -1           -1           -1            0   
12252           -1           -1            0            0            0   
12253            0            0            0           -1            0   
12269            0            0            0            0            0   

       1diff_Top15  1diff_Top10  1diff_Top5  2diff_Top50  2diff_Top40  ...  \
0                1            0           0            0            1  ...   
1               -1           -1          -1            0           -1  ...   
2               -1           -1          -1            0           -1  ...   
3                0            0           0            0            1  ...   
4                0            0           0           -1           -1  ...   
...            ...          ...         ...          ...          ...  ...   
12250            0            0           0            0            0  ...   
12251            0            0           0           -1           -1  ...   
12252            0            0           0           -1           -1  ...   
12253            0            0           0            0            0  ...   
12269            0            0           0            0            0  ...   

       Last_36month_SLAMProba_n1_win_set1_loose_set2  \
0                                          10.596505   
1                                          22.618766   
2                                          17.396638   
3                                          18.992042   
4                                          22.362136   
...                                              ...   
12250                                      24.327469   
12251                                       0.000000   
12252                                       0.000000   
12253                                      12.091107   
12269                                       0.000000   

       Last_36month_SLAMProba_n1_win_in_3sets  \
0                                    0.000000   
1                                   10.613771   
2                                    7.912850   
3                                    8.294154   
4                                    9.047715   
...                                       ...   
12250                               10.470519   
12251                                0.000000   
12252                                0.000000   
12253                                5.101706   
12269                                0.000000   

       Last_36month_SLAMProba_n1_loose_in_3sets  \
0                                      8.300251   
1                                      5.148548   
2                                      5.121087   
3                                      6.471509   
4                                     12.882980   
...                                         ...   
12250                                  3.865367   
12251                                  0.000000   
12252                                  0.000000   
12253                                  3.957785   
12269                                  0.000000   

       Last_36month_SLAMProba_n2_win_set1  \
0                               38.879191   
1                               63.355235   
2                               66.217755   
3                               51.351568   
4                               47.969118   
...                                 

In [8]:
lista_desc = [ desc_data_1, desc_data_2 ]

desc_data_12 = pd.concat( lista_desc )
desc_data_12

1diff_Top50  1diff_Top40  1diff_Top30  1diff_Top25  1diff_Top20  \
10               0            1            1            0            0   
11               1            1            1            1            0   
12               0            0            0            0            0   
13               0            0            0            0            0   
14              -1           -1            0            0            0   
...            ...          ...          ...          ...          ...   
12250            0            0            0            0            0   
12251           -1           -1           -1           -1            0   
12252           -1           -1            0            0            0   
12253            0            0            0           -1            0   
12269            0            0            0            0            0   

       1diff_Top15  1diff_Top10  1diff_Top5  2diff_Top50  2diff_Top40  ...  \
10               0            0           0            1            0  ...   
11               0            0           0            1            1  ...   
12               0            0           0            0            0  ...   
13               0            0           0            1            1  ...   
14               0            0           0            1            0  ...   
...            ...          ...         ...          ...          ...  ...   
12250            0            0           0            0            0  ...   
12251            0            0           0           -1           -1  ...   
12252            0            0           0           -1           -1  ...   
12253            0            0           0            0            0  ...   
12269            0            0           0            0            0  ...   

       Last_36month_SLAMProba_n1_win_set1_loose_set2  \
10                                         36.318794   
11                                         34.677627   
12                                         35.246897   
13                                         39.039371   
14                                          9.345104   
...                                              ...   
12250                                      24.327469   
12251                                       0.000000   
12252                                       0.000000   
12253                                      12.091107   
12269                                       0.000000   

       Last_36month_SLAMProba_n1_win_in_3sets  \
10                                  16.519582   
11                                  14.631832   
12                                  14.260887   
13                                  17.049169   
14                                   0.000000   
...                                       ...   
12250                               10.470519   
12251                                0.000000   
12252                                0.000000   
12253                                5.101706   
12269                                0.000000   

       Last_36month_SLAMProba_n1_loose_in_3sets  \
10                                    10.691244   
11                                    14.631832   
12                                    20.305979   
13                                    13.302606   
14                                     6.005939   
...                                         ...   
12250                                  3.865367   
12251                                  0.000000   
12252                                  0.000000   
12253                                  3.957785   
12269                                  0.000000   

       Last_36month_SLAMProba_n2_win_set1  \
10                              29.473131   
11                               0.000000   
12                              17.989625   
13                               0.000000   
14                              43.267653   
...                                 

In [9]:
SEGNO_1 = pd.Series( SEGNO[idx_1] )
SEGNO_2 = pd.Series( SEGNO[idx_2] )
lista_SEGNO = [SEGNO_1, SEGNO_2]
SEGNO_12 = pd.concat( lista_SEGNO )

SEGNO_MOD = []
for v in SEGNO_12 :
    if v==1 :
        SEGNO_MOD.append( 1 )
    elif v==2:
        SEGNO_MOD.append( -1 )

print( len( SEGNO_MOD ) )
print( SEGNO_MOD )
        

12270
[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [10]:
xtr, xte, ytr, yte = train_test_split( desc_data_12, SEGNO_MOD, test_size=0.30,
                                      random_state=1, shuffle=True, stratify=SEGNO_MOD  )
print( np.shape( xtr ) )
print( np.shape( ytr ) )
ytr_series = pd.Series( ytr )
xtr = pd.DataFrame.to_numpy( xtr )
ytr_series_count = ytr_series.value_counts()
print( ytr_series_count )

print( np.shape( xte ) )
print( np.shape( yte ) )
yte_series = pd.Series( yte )
xte = pd.DataFrame.to_numpy( xte )
yte_series_count = yte_series.value_counts()
print( yte_series_count )
print( yte )

(8589, 322)
(8589,)
-1    4295
 1    4294
dtype: int64
(3681, 322)
(3681,)
 1    1841
-1    1840
dtype: int64
[-1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, 1, 1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, -1, 1, -1, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 1, -1, 1, -1, -1, 1, -1, 1, 1, -1, -1, -1, -1, -1, -1, 1, 1, 1, -1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, -1, 1, -1, 1, -1, 1, -1, -1, 1, 1, 1, -1, -1, 1, -1, -1, -1, 1, -1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, 1, 1, 1, 1, -1, -1, 1, 1, -1, -1, -1, 1, 1, 1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, 1, -1, 1, 1, 1, -1, -1, -1, 1, -1, -1, 1, 1, 1, -1, -1, -1, 1, -1, 1, -1, 1, 1, 1, 1, -1, -1, 1, -1, -1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, -1, -1, 1, -1, 1, 1, -1, 1, 1, 1, 1, -1, -1, -1, -1, 1, -1, -1, 1, -1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, 1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, -1, -1, 1,

In [11]:
from sklearn.ensemble import RandomForestClassifier

estimators = [10,15,20]
max_depth = [9,10, 11, 12, 13, 14, 15]
min_samples_leaf = [8,9,10]
min_samples_split = [8,9,10]
subsample = [ 1.00]

params = []
tr_metrics = []
te_metrics = []

for e in estimators :
    for md in max_depth :
        for msl in min_samples_leaf :
            for mss in min_samples_split :
                for sbs in subsample:
                    print("n_estimators: ", e, "; max_depth: ", md, 
                      "; min_samples_leaf: ", msl, "; min_samples_split: ", mss, "; subsample: ", sbs  )
                    stringa_params = str(e)+"_"+str(md)+"_"+str(msl)+"_"+str(mss)
                    params.append( stringa_params )
                    rdfc = GradientBoostingClassifier( n_estimators=e, max_depth=md, min_samples_leaf=msl,
                              min_samples_split=mss, random_state=1, learning_rate=0.1,
                              subsample=sbs )
                    rdfc.fit( xtr, ytr )
                    Y_Tr_rdfc = rdfc.predict( xtr )
                    Y_Te_rdfc = rdfc.predict( xte )
    
                    conto = 0
                    for idx,v in enumerate ( ytr ) :
                      if v==Y_Tr_rdfc[idx] :
                        conto = conto+1
                    print("Tr: ",(conto/len(ytr))*100 )
                    tr_metrics.append((conto/len(ytr))*100)
    
                    conto = 0
                    for idx,v in enumerate ( yte ) :
                      if v==Y_Te_rdfc[idx] :
                        conto = conto+1
                    print("Te: ",(conto/len(yte))*100 )
                    te_metrics.append((conto/len(yte))*100)
                    print( confusion_matrix( yte, Y_Te_rdfc ) )

n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  8 ; min_samples_split:  8 ; subsample:  1.0
Tr:  87.4257771568285
Te:  69.30182015756587
[[1265  575]
 [ 555 1286]]
n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  8 ; min_samples_split:  9 ; subsample:  1.0
Tr:  87.4257771568285
Te:  69.30182015756587
[[1265  575]
 [ 555 1286]]
n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  8 ; min_samples_split:  10 ; subsample:  1.0
Tr:  87.4257771568285
Te:  69.30182015756587
[[1265  575]
 [ 555 1286]]
n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  9 ; min_samples_split:  8 ; subsample:  1.0
Tr:  86.89020840610083
Te:  68.94865525672371
[[1281  559]
 [ 584 1257]]
n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  9 ; min_samples_split:  9 ; subsample:  1.0
Tr:  86.89020840610083
Te:  68.94865525672371
[[1281  559]
 [ 584 1257]]
n_estimators:  10 ; max_depth:  9 ; min_samples_leaf:  9 ; min_samples_split:  10 ; subsample:  1.0
Tr:  86.89020840610083
Te:  68.94865525672

Tr:  97.70636861101408
Te:  69.1388209725618
[[1275  565]
 [ 571 1270]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  9 ; min_samples_split:  8 ; subsample:  1.0
Tr:  97.10094306671324
Te:  68.35099157837544
[[1263  577]
 [ 588 1253]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  9 ; min_samples_split:  9 ; subsample:  1.0
Tr:  97.10094306671324
Te:  68.35099157837544
[[1263  577]
 [ 588 1253]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  9 ; min_samples_split:  10 ; subsample:  1.0
Tr:  97.10094306671324
Te:  68.35099157837544
[[1263  577]
 [ 588 1253]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  10 ; min_samples_split:  8 ; subsample:  1.0
Tr:  96.11130515775993
Te:  69.1116544417278
[[1282  558]
 [ 579 1262]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  10 ; min_samples_split:  9 ; subsample:  1.0
Tr:  96.11130515775993
Te:  69.1116544417278
[[1282  558]
 [ 579 1262]]
n_estimators:  10 ; max_depth:  14 ; min_samples_leaf:  10 ; m

Tr:  95.84352078239608
Te:  68.78565607171964
[[1258  582]
 [ 567 1274]]
n_estimators:  15 ; max_depth:  12 ; min_samples_leaf:  10 ; min_samples_split:  8 ; subsample:  1.0
Tr:  95.7736639888229
Te:  70.1983156750883
[[1291  549]
 [ 548 1293]]
n_estimators:  15 ; max_depth:  12 ; min_samples_leaf:  10 ; min_samples_split:  9 ; subsample:  1.0
Tr:  95.7736639888229
Te:  70.1983156750883
[[1291  549]
 [ 548 1293]]
n_estimators:  15 ; max_depth:  12 ; min_samples_leaf:  10 ; min_samples_split:  10 ; subsample:  1.0
Tr:  95.7736639888229
Te:  70.1983156750883
[[1291  549]
 [ 548 1293]]
n_estimators:  15 ; max_depth:  13 ; min_samples_leaf:  8 ; min_samples_split:  8 ; subsample:  1.0
Tr:  98.05565257887996
Te:  69.546318935072
[[1276  564]
 [ 557 1284]]
n_estimators:  15 ; max_depth:  13 ; min_samples_leaf:  8 ; min_samples_split:  9 ; subsample:  1.0
Tr:  98.05565257887996
Te:  69.546318935072
[[1276  564]
 [ 557 1284]]
n_estimators:  15 ; max_depth:  13 ; min_samples_leaf:  8 ; min_samp

Tr:  93.07253463732681
Te:  70.27981526759032
[[1288  552]
 [ 542 1299]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  8 ; min_samples_split:  8 ; subsample:  1.0
Tr:  96.37908953312376
Te:  69.22032056506384
[[1265  575]
 [ 558 1283]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  8 ; min_samples_split:  9 ; subsample:  1.0
Tr:  96.37908953312376
Te:  69.22032056506384
[[1265  575]
 [ 558 1283]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  8 ; min_samples_split:  10 ; subsample:  1.0
Tr:  96.37908953312376
Te:  69.22032056506384
[[1265  575]
 [ 558 1283]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  9 ; min_samples_split:  8 ; subsample:  1.0
Tr:  95.75037839096518
Te:  70.0081499592502
[[1271  569]
 [ 535 1306]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  9 ; min_samples_split:  9 ; subsample:  1.0
Tr:  95.75037839096518
Te:  70.0081499592502
[[1271  569]
 [ 535 1306]]
n_estimators:  20 ; max_depth:  11 ; min_samples_leaf:  9 ; min

In [12]:
data_ottimizzazione = pd.DataFrame()
data_ottimizzazione['params'] = params
data_ottimizzazione['Tr'] = tr_metrics
data_ottimizzazione['Te'] = te_metrics
data_ottimizzazione

params         Tr         Te
0       10_9_8_8  87.425777  69.301820
1       10_9_8_9  87.425777  69.301820
2      10_9_8_10  87.425777  69.301820
3       10_9_9_8  86.890208  68.948655
4       10_9_9_9  86.890208  68.948655
..           ...        ...        ...
184    20_15_9_9  99.487717  69.247487
185   20_15_9_10  99.487717  69.247487
186   20_15_10_8  99.324718  68.894322
187   20_15_10_9  99.324718  68.894322
188  20_15_10_10  99.324718  68.894322

[189 rows x 3 columns]

In [13]:
data_ottimizzazione.sort_values( by=['Te'], ascending=False )

params         Tr         Te
143  20_10_10_10  93.072535  70.279815
141   20_10_10_8  93.072535  70.279815
142   20_10_10_9  93.072535  70.279815
87    15_11_10_8  94.085458  70.252649
88    15_11_10_9  94.085458  70.252649
..           ...        ...        ...
56    10_15_8_10  98.521365  68.296659
54     10_15_8_8  98.521365  68.296659
58     10_15_9_9  97.380370  68.242325
57     10_15_9_8  97.380370  68.242325
59    10_15_9_10  97.380370  68.242325

[189 rows x 3 columns]

In [14]:
data_ottimizzazione.sort_values( by=['Tr'], ascending=False )

params         Tr         Te
180   20_15_8_8  99.569216  68.541157
182  20_15_8_10  99.569216  68.541157
181   20_15_8_9  99.569216  68.541157
185  20_15_9_10  99.487717  69.247487
184   20_15_9_9  99.487717  69.247487
..          ...        ...        ...
4      10_9_9_9  86.890208  68.948655
3      10_9_9_8  86.890208  68.948655
8    10_9_10_10  86.505996  69.410486
7     10_9_10_9  86.505996  69.410486
6     10_9_10_8  86.505996  69.410486

[189 rows x 3 columns]